version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: final
    image: pm-app-api-dev
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:password@host:5432/pm_db?schema=public"
    volumes:
      - ./:/workspace:cached
      - /workspace/node_modules
